name: CI

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: djflabkt

jobs:
  build:
    name: Build & Publish

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v6.0.1
        with:
          search_commit_body: true
          bump_each_commit: true

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Fat JAR
        run: ./gradlew shadowjar
        env:
          DJFLAB_VERSION: ${{ steps.version.outputs.version }}

      - name: Log in to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#        with:
#          platforms: 'linux/amd64,linux/arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase repo owner name
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Build and push container image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          platforms: linux/amd64 #,linux/arm64
